### ISSUE TITLE
how can I make requests batch and ignore their result?

### ISSUE THREAD

**Issue by zhenbianshu** [tramchamploo/buffer-slayer#125]
I found the async sender keeps many Futures to wait for result  while making request batch. When high concurrency occurs,  it will keeps many thread waiting. So can I submit a request and finish the thread to ignore the result ?

**Comment by tramchamploo** [comment]
首先，future和线程等待并没有直接关系。如果你不在你的线程上调future.await()，是没有业务线程会被阻塞的

**Comment by zhenbianshu** [comment]
我的意思是会有很多 future 线程存在，无论我是否 wait 这个线程。
希望的是我能把请求都同步提交到一个池子里，然后有一个后台线程消费池子里的请求再合并发起。

**Comment by tramchamploo** [comment]
我理解你说的future线程就是业务线程，线程和future之间没有绑定关系。对于每个请求返回一个future是特性之一，就好比一些异步http框架请求时会返回future或需要指定callback一样。
